version: "3.0"
services:
  map:
    build: .
    ports:
      - "8383:80"
    environment:
      BASISKAART_DB_NAME: AMS_Mapserver_ma_2018
      BASISKAART_DB_USER: AMS_Mapserver_ma_2018
      BASISKAART_DB_PASSWORD: AMS_Mapserver_ma_2018
      BASISKAART_DB_HOST: postgres
      BASISKAART_DB_PORT: 5432
      MAP_URL: "http://localhost"
    volumes:
      - /tmp/srv/:/srv/
      - /home/niene/Documents/00_Projecten/2017_03_Amsterdam_mapserver:/srv/mapserver/
    networks:
      - 201805amsterdammapserver_default
    external_links:
      - 201805amsterdammapserver_postgres_1:postgres

networks:
  201805amsterdammapserver_default:
    external: true