database:
  image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
  ports:
    - "5432"
  environment:
    POSTGRES_PASSWORD: insecure

map:
  build: .
  ports:
    - "8989:80"
  external_links:
    - "handelsregister_database_1:handelsregister_db"
  environment:
    ATLAS_DB_NAME: atlas
    ATLAS_DB_USER: postgres
    ATLAS_DB_PASSWORD: insecure

    NAP_DB_NAME: nap
    NAP_DB_USER: postgres
    NAP_DB_PASSWORD: insecure

    MILIEUTHEMAS_DB_NAME: milieuthemas
    MILIEUTHEMAS_DB_USER: postgres
    MILIEUTHEMAS_DB_PASSWORD: insecure

    PANORAMA_DB_NAME: panorama
    PANORAMA_DB_USER: panorama
    PANORAMA_DB_PASSWORD: insecure

    PARKEERVAKKEN_DB_NAME: parkeervakken
    PARKEERVAKKEN_DB_USER: postgres
    PARKEERVAKKEN_DB_PASSWORD: insecure

    BASISKAART_DB_NAME: basiskaart
    BASISKAART_DB_USER: postgres
    BASISKAART_DB_PASSWORD: insecure

    HANDELSREGISTER_DB_NAME: handelsregister
    HANDELSREGISTER_DB_USER: handelsregister
    HANDELSREGISTER_DB_PASSWORD: insecure

