#!/usr/bin/env bash

set -e
set -u



HANDELSREGISTER_DB_HOST=${HANDELSREGISTER_DB_PORT_5432_TCP_ADDR:-handelsregister-read.service.consul}
HANDELSREGISTER_DB_PORT=${HANDELSREGISTER_DB_PORT_5432_TCP_PORT:-5432}
HANDELSREGISTER_DB_USER=${HANDELSREGISTER_DB_USER:-${HANDELSREGISTER_DB_NAME}}

echo Creating configuration files


cat > /srv/mapserver/connection_handelsregister.inc <<EOF
CONNECTIONTYPE postgis
CONNECTION "host=${HANDELSREGISTER_DB_HOST} dbname=${HANDELSREGISTER_DB_NAME} user=${HANDELSREGISTER_DB_USER} password=${HANDELSREGISTER_DB_PASSWORD} port=${HANDELSREGISTER_DB_PORT}"
PROCESSING "CLOSE_CONNECTION=DEFER"
EOF

echo Starting server
apachectl -D FOREGROUND

